# Generated by Django 5.1.1 on 2024-10-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactMe',
            fields=[
                ('cno', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=100)),
            ],
        ),
    ]
