# Generated by Django 5.1.1 on 2024-10-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactme',
            name='uname',
            field=models.CharField(max_length=60),
        ),
    ]
